#!/bin/sh

if [ $(uname -s) == 'Darwin' ]; then

	# On Mac OS, symlinks are ignored!
	dir=$(dirname $0)
else

	dir=$(dirname $(readlink -f $0))
fi

rm -rf ${dir}/lib

coffee -b -wco ${dir}/lib ${dir}/src &
